# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'MIEMApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MIEMApp
  pod 'Alamofire', '~> 5.2'
  pod 'GoogleSignIn'
  pod 'EzPopup'
  pod 'AppAuth'
  pod 'BEMCheckBox'
end
